name: CI/CD

on:
  push:
    paths:
      - src/**
      - .github/**
    branches:
      - release/*
      - hotfix/*
      - canary
      - master
    tags:
      - v*

  pull_request:
    paths:
      - src/**
    branches:
      - canary
      - master

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.device }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        device:
          - any
          - cpuonly

        include:
          - os: ubuntu-latest # Ubuntu
            platform: ubuntu
            python: python3
          - os: windows-latest # Windows
            platform: windows
            python: python
          - os: macOS-latest # macOS
            platform: macos
            python: python3

        exclude:
          - os: macOS-latest
            device: any

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Use Python 3.7
        uses: actions/setup-python@v1
        if: runner.os != 'macOS'
        with:
          python-version: 3.7
          architecture: x64

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use Yarn
        run: npm install -g yarn

      - name: Setup
        if: matrix.platform == 'macos'
        run: brew install p7zip openblas

      - name: Setup (NodeJS)
        working-directory: src/scripts
        run: yarn install

      - name: Setup (Python)
        working-directory: src
        run: ${{ matrix.python }} -m pip install -r requirements.txt

      - name: Setup (CUDA)
        working-directory: src
        if: matrix.device == 'any'
        run: ${{ matrix.python }} -m pip install cupy-cuda102==7.6.0

      - name: Build NumPy
        working-directory: src
        if: matrix.platform == 'macos'
        run: |
          cp .numpy-site.cfg ~/
          ${{ matrix.python }} -m pip uninstall numpy --yes
          ${{ matrix.python }} -m pip install --no-binary :all: numpy
          ${{ matrix.python }} -c "import numpy; print(numpy.show_config())"

      - name: Build
        working-directory: src/scripts
        run: ${{ matrix.python }} build.py --debug

      - uses: actions/upload-artifact@v2
        with:
          name: waifu2x-${{ matrix.platform }}-${{ matrix.device }}
          path: dist/waifu2x/

      - name: Deploy
        working-directory: src/scripts
        continue-on-error: true
        timeout-minutes: 20
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          BUILD_PLATFORM: ${{ matrix.platform }}
          BUILD_DEVICE: ${{ matrix.device }}
          DEPLOY_ENCRYPT_KEY: ${{ secrets.DEPLOY_ENCRYPT_KEY }}
          DEPLOY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_GITHUB_OWNER: dreamnettech
          DEPLOY_DREAMLINKCLUSTER_USERNAME: dreamnet
          DEPLOY_DREAMLINKCLUSTER_PASSWORD: ${{ secrets.DEPLOY_DREAMLINKCLUSTER_PASSWORD }}
          DEPLOY_MEGA_EMAIL: ${{ secrets.DEPLOY_MEGA_EMAIL }}
          DEPLOY_MEGA_PASSWORD: ${{ secrets.DEPLOY_MEGA_PASSWORD }}
          DEPLOY_MEGA_FOLDER: "/Projects/Waifu2X/Releases/"
        run: node deploy.js